@startmindmap
*:001.us.sh

<code>
	fns__gig_d_mkdr

	local fns__dr_dta=$(fns__gig_d_echo)

	l_00_echo_warn "\$fns__dr_dta=$fns__dr_dta"

	fns__body
	fns__hdr
	fns__chpt
</code>
;
**:001.01.gig_d_mkdr.us.sh

<code>
	fns__gig_d_mkdr() {

		local pr_dr=$(l_01_prs_f -d $arg_2)
		local nm_dr=_$(l_01_prs_f -ne $arg_2).d

		if ! (
			rm -f $pr_dr/$nm_dr
			mkdir $pr_dr/$nm_dr
		) >/dev/null; then
			return 1
		fi
	}
</code>
;
**:001.03.body.us.sh

<code>
	fns__body() {
		fns_bsh_002_d2md_1 $arg_1 $fns__dr_dta/body.md
	}
</code>
;
**:001.04.hdr.us.sh

<code>
	fns__hdr() {
		grep "^#" $fns__dr_dta/body.md | grep -v "^#!" >$fns__dr_dta/hdr.md
	}
</code>
;
**:001.05.chpt.us.sh

<code>
	fns__chpt() {
		#-- $fns__dr_dta/hdr.md
		#-- grep -o -P '(?<=<!-- { -->).*(?=<!-- } -->)' $dr_pth/hdr.lst > $dr_pth/chpt.lst

		grep -o -P '(?<=<!-- { -->).*(?=<!-- } -->)' $fns__dr_dta/hdr.md >$fns__dr_dta/chpt.md
	}
</code>
;
**:001.06.gig_d_echo.us.sh

<code>
	fns__gig_d_echo() {
		local pr_dr=$(l_01_prs_f -d $arg_2)
		local nm_dr=_$(l_01_prs_f -ne $arg_2).d

		echo "$pr_dr/$nm_dr"
	}
</code>
;
*:002.us.sh

<code>

fns__prp_body
fns__toc2md

</code>
;
**:002.02.prp_body.us.sh

<code>
	fns__prp_body() {

		# $dr_pth/.cdn/pre1.md
		# $fns__dr_dta/chpt.md
		# $fns__dr_dta/body.md
		#! $fns__dr_dta/body_toc.md result
		cat $dr_pth/.cdn/pre1.md | cat - $fns__dr_dta/body.md >$fns__dr_dta/body_toc.md

	}
</code>
;
**:002.01.toc2md.us.sh

<code>
	fns__toc2md() {

		# $fns__dr_dta/chpt.md
		# $fns__dr_dta/body.md
		#! $fns__dr_dta/body_toc.md result
		local pnt=
		local anc=
		local str=
		local rnd_1=

		IFS=$'\n'
		for str in $(<$fns__dr_dta/chpt.md); do
			echo "$str"
			#  - <a href=#35a6b9d026864bd79ab8bfd21541e3fa> Local repo opuses</a>
			#<a id="16d01bbb8a3048f18d8665782e885627"></a>
			rnd_1=$(tr -dc 0-9A-Za-z </dev/urandom | head -c 32)
			pnt="- <a href=#$rnd_1>$str</a>"
			anc="<a id=\"$rnd_1\"></a>"
			#sed '/^b/i ascsdc' init/init.fl > res.fl

			eval "sed -i '/$str/i $anc' $fns__dr_dta/body_toc.md"
			eval "sed -i '/ETOC/i $pnt' $fns__dr_dta/body_toc.md"



		done
		IFS=

		lfoe_path_to_var $fns__dr_dta/body_toc.md
		read -p fns__toc2md
	}
</code>
;
*:00X.XXX.us.sh

<code>
. .bashrc
</code>
;
@endmindmap